# This is a basic workflow that is manually triggered

name: Initial Setup
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Repo Name'
        default: 'Repo-Template'
        required: true
        type: string
      version:
        description: 'Desired Version'
        default: 1726
        required: false
        type: number
      owner:
        description: 'Repo Owner'
        default: 'Scott Clay'
        required: true
        type: string
      product_type:
        description: 'Repo Type'
        type: choice
        default: 'Spark'
        options:
        - 'Spark'
        - 'SQL'
        - 'Lambda'
        required: true
      machine_learning:
        description: 'Enable ML'
        type: boolean
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"


  build-yaml:
    runs-on: ubuntu-latest
    steps:
    -  run: |
        echo "Install required dependencies"
        sudo apt-get update
        sudo apt-get install python3
    -  env:
        GITHUB_TOKEN: ${{ secrets.YAML_TEMPLATE_ACTION_TOKEN }}
        GHA_CATALOG: hello
        GHA_NAME: ${{ inputs.name }}
        GHA_OWNER: ${{ inputs.owner }}
        GHA_TYPE: ${{ inputs.product_type }}
        #GHA_VERSION:
       name: Check out repo's default branch
       uses: actions/checkout@v4

    -  env:
        GHA_CATALOG: hello
        GHA_NAME: ${{ inputs.name }}
        GHA_OWNER: ${{ inputs.owner }}
        GHA_TYPE: ${{ inputs.product_type }}
       run: |
        echo "Run, Build Application using scripts"
        python3 gen_yaml.py
    -  env:
        GITHUB_TOKEN: ${{ secrets.YAML_TEMPLATE_ACTION_TOKEN }}
       name: create pull request
       run: |
        git checkout -b gha_create_yaml_file
        git config --global user.email "citool@scottclay.email"
        git config --global user.name "citool"
        git add magic.yaml
        git commit -m "Add yaml file"
        git push origin HEAD
        gh pr create -B main -H gha_create_yaml_file --title 'Merge gha_create_yaml_file into main' --body 'Created by Github Action'
